tasks:
  - label: "Text2SparqlExecEvalListBeastiaryTurtleSubgraph"
    class: "Text2SparqlExecEvalListBeastiary"
    params:
      - kgInfoType: "subgraph"
        kgInfoFormat: "turtle"
  # - label: "Text2SparqlExecEvalListBeastiaryJsonldSubgraph"
  #   class: "Text2SparqlExecEvalListBeastiary"
  #   params:
  #     - kgInfoType: "subgraph"
  #       kgInfoFormat: "json-ld"
  - label: "Text2SparqlExecEvalListBeastiaryTurtleSchema"
    class: "Text2SparqlExecEvalListBeastiary"
    params:
      - kgInfoType: "schema"
        kgInfoFormat: "turtle"
  # - label: "Text2SparqlExecEvalListBeastiaryJsonldSchema"
  #   class: "Text2SparqlExecEvalListBeastiary"
  #   params:
  #     - kgInfoType: "schema"
  #       kgInfoFormat: "json-ld"
  - label: "Text2SparqlExecEvalListBeastiaryTurtleSubschema"
    class: "Text2SparqlExecEvalListBeastiary"
    params:
      - kgInfoType: "subschema"
        kgInfoFormat: "turtle"
  # - label: "Text2SparqlExecEvalListBeastiaryJsonldSubschema"
  #   class: "Text2SparqlExecEvalListBeastiary"
  #   params:
  #     - kgInfoType: "subschema"
  #       kgInfoFormat: "json-ld"
  - label: "Text2SparqlExecEvalListBeastiaryIris"
    class: "Text2SparqlExecEvalListBeastiary"
    params:
      - kgInfoType: "iris"
  - Text2SparqlExecEvalListLcQuad
  - Text2SparqlExecEvalListOrganizational
  - Text2SparqlExecEvalListOrgaNumerical
  - Text2SparqlExecEvalListSciQA
  - label: "Text2SparqlExecEvalListCoypuMiniTurtleGraph"
    class: Text2SparqlExecEvalListCoypuMini
    params:
      - kgInfoType: "graph"
        kgInfoFormat: "turtle"
  - label: "Text2SparqlExecEvalListCoypuMiniJsonldGraph"
    class: Text2SparqlExecEvalListCoypuMini
    params:
      - kgInfoType: "graph"
        kgInfoFormat: "json-ld"
  - label: "Text2SparqlExecEvalListCoypuMiniTurtleMSchema"
    class: Text2SparqlExecEvalListCoypuMini
    params:
      - kgInfoType: "minischema"
        kgInfoFormat: "turtle"
  - label: "Text2SparqlExecEvalListCoypuMiniJsonldMSchema"
    class: Text2SparqlExecEvalListCoypuMini
    params:
      - kgInfoType: "minischema"
        kgInfoFormat: "json-ld"
  - label: "Text2SparqlExecEvalListCoypuMiniIris"
    class: Text2SparqlExecEvalListCoypuMini
    params:
      - kgInfoType: "iris"
  - SparqlSyntaxFixingListLcQuad
  - label: "Text2AnswerListOrgaTurtle"
    class: "Text2AnswerListOrganizational"
    params:
      - graphFormat: "turtle"
  - label: "Text2AnswerListOrgaJsonld"
    class: "Text2AnswerListOrganizational"
    params:
      - graphFormat: "json-ld"
  - label: "Sparql2AnswerListOrgaTurtle"
    class: "Sparql2AnswerListOrganizational"
    params:
      - graphFormat: "turtle"
  - label: "Sparql2AnswerListOrgaJsonld"
    class: "Sparql2AnswerListOrganizational"
    params:
      - graphFormat: "json-ld"
models:
  - label: Gemini-1.0-Pro
    class: ModelGoogle
    params:
      - model: 'gemini-1.0-pro'
  - label: Gemini-1.5-Pro
    class: ModelGoogle
    params:
      - model: 'models/gemini-1.5-pro-latest'
  # - label: "GPT-3.5t16k_2023-11"
  #   class: ModelGpt
  #   params:
  #     - model: "gpt-3.5-turbo-1106" #has 16k
  - label: "GPT-3.5t16k_2024-01"
    class: ModelGpt
    params:
      - model: "gpt-3.5-turbo-0125" # has 16k context, 4k output limit
  - label: GPT-4t_2023-11
    class: ModelGpt
    params:
      - model: "gpt-4-1106-preview" # has 128k
  - label: "GPT-4t_2024-04"
    class: ModelGpt
    params:
      - model: "gpt-4-turbo-2024-04-09"
  # - label: Claude-1.3
  #   class: ModelClaude
  #   params:
  #     - model: "claude-1.3"
  # - label: Claude-1.3-100k
  #   class: ModelClaude
  #   params:
  #     - model: "claude-1.3-100k"
  # - label: Claude-2.0
  #   class: ModelClaude
  #   params:
  #     - model: "claude-2.0" #has 100k
  - label: Claude-2.1
    class: ModelClaude
    params:
      - model: "claude-2.1" #has 200k
  - label: Claude-3-opus
    class: ModelClaude
    params:
      - model: "claude-3-opus-20240229" #has 200k input, 4k output limit
  - label: Claude-3-sonnet
    class: ModelClaude
    params:
      - model: "claude-3-sonnet-20240229" #has 200k input, 4k output limit
  - label: Claude-3-haiku
    class: ModelClaude
    params:
      - model: "claude-3-haiku-20240307" #has 200k input, 4k output limit
sizes:
  - 1000
iterations: 20
